travis:
  secure:
    BINSTAR_TOKEN: JgKX/8bmurGEjmRE998DbKrq9wZb0h1HOgg+piiz3a7mkwiKppH/qlqOu6GBGFjfWy1ctvJRkiIELwAHquZ2ML9kYTiUfFXwF1XZW8gUXG8t7H+qc4AZUmGbyShNdnHyIBt7RQPYgRYNEpvxdAwC4BAUOrsjivwhsyCTcc98kYc9TmQCQ8WbfbzXJyhM5/W9bVS5Gnpmn3VZ+gKLGKnxTJcu6AFxqjYbOK5mkf+ONfqJtiZ5R/8hLAocfjIKoJNCUfqHTPT3jL0WUMfmMWGqweTWQNyOOsml4Xya0ZrU5vsKZCFvDvKdGr2ktFy0n3i1bLaH7+4TqS2GtNaqctrykZmB99uSy5dJmy1KdaGVfnhNsz8dGF9Zf2dipAtXRPEgeTVhnjEL0m7rMGdktFwAySAv5U35x0mnw9FaWxube1s0H19StWf6F7eXBEniKPeO7WKslFTcb5ZTCKmr8Y8hO/suq6VvOxIEK3Jf9Y88ej9UsTbK+VTLULsZAYuNnlpeCBW6rWv1VvdCZjvzayEkVyKv0foZ8IBZ0UU51GQxFoZISC+dvl0Gwu9ml3v3Q8vKi93L+O164KaPbJuiP0AWROmMfMlF7kQwNHDUmWdy98AqUVcftrF0d/0zW+QkxlFy8Tp/KBHhp5uiRWIv9ziCuVdcuByr/+drRRE7XQWs3fc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
