travis:
  secure:
    BINSTAR_TOKEN: LA2U3bYJHoqf7sV8SaYsUXT5gZ3daepv9OiYcLNEwvzUbPlUSvTPogyPytrhn9nGMxSi+6S23o1oycCchKR74yQyF1PNJokJI7TyioIw9xGtC0QBaMvtuQhuN2zAx2NAli8dV9hB5JPX2nFqD/vTRGzvqYb83qMVQGS8FvZigiPGz0lA3OylMvK5xd2vkdlAx2745tSbN2p7adwdOawteNXpBmzV9Vv+YB4s2p3SVUVodsTaw+sYKFftp/AQkRzpuK6X2znUy2WtTh5hnWYHcRg/ePMgF+20f/YosxlZHsRpsru7rxGfSRnZpHRE8WUw05nR7av7IilExBUFztWqmECmtz0P7V2nmIQjJbMf76mu8PKGgQjIW6IKaohRJ+an6Ifd2AODYxlTmaCdMDXXrk7QywmZ3koXY7S6YV3WIODv1eHx1s9YMAdrDRgoK5Ykpd5ipzK1lO+rMU1S+agqmDB6wDXZsJZ1ses0fx/n9+ljMXTx35VomyPXas5wiv00PTtz9us4SStG/GvA9eNnuU6lAaP7ydODTDGUL6akj3NL6u5jLhu0gyOvp6O4XiHoJ/VMzbVD9Mc/MTdJHRoDVcDSbn+fB+8F4OxAQUiISI6FqpEC1nkaFnTFntwVP+smbKCJDQ1hPnLqVp3C3qxU6oq1KPHhIe9VQsW8cCZf27A=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
