travis:
  secure:
    BINSTAR_TOKEN: U3GFtombGExIHt2Kmh9WasDA87gjYHTcMDZmKuuloPeYjMBQnd3F8lAICrU2/8xeUGIoqBvU/lAdcFIGkWXSIGWwqzF8sicB87/8V+a0bVOEiAPlGaBPemnhUCGV2+LI5Skfo71WV9824lUoiZtJWkExe26nnbxW5CPgA1cHFPuEn3vGXCR0mDvbaWrB3UNuahmjJAUVUn+L+dr2zpBMwRWqlDqsILYIuJEnJqby9VWnJrm2AlumU7Sf7iX02bVV7eahaFByhiZXZPP6GEwziiaCBgWwkjj3JnTf1QvdfyKBGa4eDIw2U8lEuquG7HYE1G7SRCP80Vgp/yhnVrG1oHPAOsvDoCOMLe3gpz3KbxBCs8RCHm6g9U9rOToMK8k5xVl3blcarNhWHHe6AR//pDOg7EzaBfnsgki7IfIARo051u5TPVtjB8sx8yDtyiQYGSB8vIec4UJS3ryF45Z2wr363nEzB50JWWmPTjsUOHpeGrKDErt1gi58KQluvoECvDq7biBPCLpiXSd1b/SwoHL3FzZJoItpMFp9SlbW9K/I+hRcyZb+OSs7erS50gBGgKPPIgNWMHkslKLMFIG6hNWwuEUYc+7YqaT5UfAAd/wkVB+Yb+8vjzQjF6AvdtDhD5ToxLGkeWBKBOaS6nVDd7arLlpCSMPRZi00El82o5g=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
